# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809e900e7a7975ee95b8b331188fcaf6bff33cf81d871223f590b1cc59df35f281e6752be3fc29f13329c8badd709395bd0b2d09b7fc1b94a6060674ce1b4ecf

test:
  secret_key_base: 04cac97930963f00d2ce059abbf40e276a06930be49e27a93713e25ecfbb5c852c38f16204c6d9d940cabfb7ccc4d1dd1e84bb2978db3d14df30bc5017b29e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
